<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DomainObjectModel_Subdivision', 'main');

/**
 * DomainObjectModel_BaseSubdivision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $subdivision_id
 * @property string $subdivision_alias
 * @property string $subdivision_title
 * @property enum $subdivision_status
 * @property timestamp $created
 * @property timestamp $updated
 * @property Doctrine_Collection $City
 * @property Doctrine_Collection $Office
 * @property Doctrine_Collection $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class DomainObjectModel_BaseSubdivision extends DomainObjectModel
{
    public function setTableDefinition()
    {
        $this->setTableName('moihottur__subdivision');
        $this->hasColumn('subdivision_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('subdivision_alias', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('subdivision_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('subdivision_status', 'enum', 8, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'ENABLED',
              1 => 'DISABLED',
             ),
             'primary' => false,
             'default' => 'ENABLED',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DomainObjectModel_City as City', array(
             'local' => 'subdivision_id',
             'foreign' => 'subdivision_id'));

        $this->hasMany('DomainObjectModel_Office as Office', array(
             'local' => 'subdivision_id',
             'foreign' => 'subdivision_id'));

        $this->hasMany('DomainObjectModel_User as User', array(
             'local' => 'subdivision_id',
             'foreign' => 'subdivision_id'));
    }
}