<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DomainObjectModel_Discount', 'main');

/**
 * DomainObjectModel_BaseDiscount
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $discount_id
 * @property enum $discount_type
 * @property decimal $discount_price_min
 * @property decimal $discount_price_max
 * @property integer $touroperator_id
 * @property integer $country_id
 * @property integer $departure_city_id
 * @property decimal $discount_percent
 * @property integer $discount_qnt
 * @property timestamp $created
 * @property timestamp $updated
 * @property DomainObjectModel_Touroperator $Touroperator
 * @property DomainObjectModel_Country $Country
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class DomainObjectModel_BaseDiscount extends DomainObjectModel
{
    public function setTableDefinition()
    {
        $this->setTableName('moihottur__discount');
        $this->hasColumn('discount_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('discount_type', 'enum', 8, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' =>
             array(
              0 => 'DISCOUNT',
              1 => 'PROMO',
             ),
             'primary' => false,
             'default' => 'DISCOUNT',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('discount_price_min', 'decimal', 9, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '9',
             'scale' => ' 2',
             ));
        $this->hasColumn('discount_price_max', 'decimal', 9, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '9',
             'scale' => ' 2',
             ));
        $this->hasColumn('touroperator_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('country_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('departure_city_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('discount_percent', 'decimal', 5, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '5',
             'scale' => ' 2',
             ));
        $this->hasColumn('discount_qnt', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DomainObjectModel_Touroperator as Touroperator', array(
             'local' => 'touroperator_id',
             'foreign' => 'touroperator_id'));

        $this->hasOne('DomainObjectModel_Country as Country', array(
             'local' => 'country_id',
             'foreign' => 'country_id'));
    }
}