<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DomainObjectModel_User', 'main');

/**
 * DomainObjectModel_BaseUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $user_id
 * @property integer $subdivision_id
 * @property integer $office_id
 * @property string $user_login
 * @property string $user_identifier
 * @property string $user_name
 * @property enum $user_role
 * @property timestamp $user_visited
 * @property string $user_ip
 * @property string $user_froms
 * @property enum $user_status
 * @property timestamp $created
 * @property timestamp $updated
 * @property DomainObjectModel_Subdivision $Subdivision
 * @property DomainObjectModel_Office $Office
 * @property Doctrine_Collection $Faq
 * @property Doctrine_Collection $Feedback
 * @property Doctrine_Collection $Product
 * @property Doctrine_Collection $Request
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class DomainObjectModel_BaseUser extends DomainObjectModel
{
    public function setTableDefinition()
    {
        $this->setTableName('moihottur__user');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('subdivision_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('office_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('user_login', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '100',
             ));
        $this->hasColumn('user_identifier', 'string', 32, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '32',
             ));
        $this->hasColumn('user_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('user_role', 'enum', 9, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' =>
             array(
              0 => 'DEVELOPER',
              1 => 'ADMIN',
              2 => 'DIRECTOR',
              3 => 'MODERATOR',
              4 => 'OPERATOR',
              5 => 'SELLER',
             ),
             'primary' => false,
             'default' => 'OPERATOR',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '9',
             ));
        $this->hasColumn('user_visited', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('user_ip', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('user_froms', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('user_status', 'enum', 8, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' =>
             array(
              0 => 'ENABLED',
              1 => 'DISABLED',
             ),
             'primary' => false,
             'default' => 'ENABLED',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DomainObjectModel_Subdivision as Subdivision', array(
             'local' => 'subdivision_id',
             'foreign' => 'subdivision_id'));

        $this->hasOne('DomainObjectModel_Office as Office', array(
             'local' => 'office_id',
             'foreign' => 'office_id'));

        $this->hasMany('DomainObjectModel_Faq as Faq', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $this->hasMany('DomainObjectModel_Feedback as Feedback', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $this->hasMany('DomainObjectModel_Product as Product', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $this->hasMany('DomainObjectModel_Request as Request', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));
    }
}